// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Message.proto

package br.ufs.dcomp.ChatRabbitMQ;

public final class MessageData {
  private MessageData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatRabbitMQ.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Nome do Sender
     * </pre>
     *
     * <code>optional string Sender = 1;</code>
     */
    java.lang.String getSender();
    /**
     * <pre>
     * Nome do Sender
     * </pre>
     *
     * <code>optional string Sender = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    java.lang.String getDate();
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <pre>
     * Hour de envio
     * </pre>
     *
     * <code>optional string Hour = 3;</code>
     */
    java.lang.String getHour();
    /**
     * <pre>
     * Hour de envio
     * </pre>
     *
     * <code>optional string Hour = 3;</code>
     */
    com.google.protobuf.ByteString
        getHourBytes();
 
    /**
     * <pre>
     * Informa o nome do group, se a mensagem for para um group
     * </pre>
     *
     * <code>optional string group = 4;</code>
    */
    java.lang.String getGroup();
    /**
     * <pre>
     * Informa o nome do group, se a mensagem for para um group
     * </pre>
     *
     * <code>optional string group = 4;</code>
    */
    com.google.protobuf.ByteString
        getGroupBytes();
    
    /**
     * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.MessageData.Content getContent();
    /**
     * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.MessageData.ContentOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code ChatRabbitMQ.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements 
      MessageOrBuilder { 
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      Sender_ = "";
      data_ = "";
      Hour_ = ""; 
      group_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              Sender_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              Hour_ = s;
              break;
            } 
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 42: {
              br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder subBuilder = null;
              if (Content_ != null) {
                subBuilder = Content_.toBuilder();
              }
              Content_ = input.readMessage(br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(Content_);
                Content_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.MessageData.Message.class, br.ufs.dcomp.ChatRabbitMQ.MessageData.Message.Builder.class);
    }

    public static final int Sender_FIELD_NUMBER = 1;
    private volatile java.lang.Object Sender_;
    /**
     * <pre>
     * Nome do Sender
     * </pre>
     *
     * <code>optional string Sender = 1;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = Sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        Sender_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Nome do Sender
     * </pre>
     *
     * <code>optional string Sender = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = Sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Data de envio
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int Hour_FIELD_NUMBER = 3;
    private volatile java.lang.Object Hour_;
    /**
     * <pre>
     * Hour de envio
     * </pre>
     *
     * <code>optional string Hour = 3;</code>
     */
    public java.lang.String getHour() {
      java.lang.Object ref = Hour_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        Hour_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Hour de envio
     * </pre>
     *
     * <code>optional string Hour = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHourBytes() {
      java.lang.Object ref = Hour_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Hour_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 4;
    private volatile java.lang.Object group_;
    /**
     * <pre>
     * Informa o nome do group, se a mensagem for para um group
     * </pre>
     *
     * <code>optional string group = 4;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Informa o nome do group, se a mensagem for para um group
     * </pre>
     *
     * <code>optional string group = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
  
    public static final int Content_FIELD_NUMBER = 5;
    private br.ufs.dcomp.ChatRabbitMQ.MessageData.Content Content_;
    /**
     * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
     */
    public boolean hasContent() {
      return Content_ != null;
    }
    /**
     * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.MessageData.Content getContent() {
      return Content_ == null ? br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.getDefaultInstance() : Content_;
    }
    /**
     * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.MessageData.ContentOrBuilder getContentOrBuilder() {
      return getContent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, Sender_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      if (!getHourBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, Hour_);
      } 
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, group_);
      }
      if (Content_ != null) {
        output.writeMessage(5, getContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, Sender_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      if (!getHourBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, Hour_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, group_);
      } 
      if (Content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getContent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.MessageData.Message)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.MessageData.Message other = (br.ufs.dcomp.ChatRabbitMQ.MessageData.Message) obj;

      boolean result = true;
      result = result && getSender()
          .equals(other.getSender());
      result = result && getDate()
          .equals(other.getDate());
      result = result && getHour()
          .equals(other.getHour()); 
      result = result && getGroup()
          .equals(other.getGroup());    
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + Sender_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + Hour_FIELD_NUMBER;
      hash = (53 * hash) + getHour().hashCode(); 
      hash = (53 * hash) + getGroup().hashCode();
      if (hasContent()) {
        hash = (37 * hash) + Content_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.MessageData.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatRabbitMQ.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatRabbitMQ.Message)
        br.ufs.dcomp.ChatRabbitMQ.MessageData.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.MessageData.Message.class, br.ufs.dcomp.ChatRabbitMQ.MessageData.Message.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.MessageData.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        Sender_ = "";

        data_ = "";

        Hour_ = ""; 

        group_ = "";

        if (ContentBuilder_ == null) {
          Content_ = null;
        } else {
          Content_ = null;
          ContentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Message_descriptor;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Message getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.Message.getDefaultInstance();
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Message build() {
        br.ufs.dcomp.ChatRabbitMQ.MessageData.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Message buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.MessageData.Message result = new br.ufs.dcomp.ChatRabbitMQ.MessageData.Message(this);
        result.Sender_ = Sender_;
        result.data_ = data_;
        result.Hour_ = Hour_; 
        result.group_ = group_;
        
        if (ContentBuilder_ == null) {
          result.Content_ = Content_;
        } else {
          result.Content_ = ContentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.MessageData.Message) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.MessageData.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.MessageData.Message other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.MessageData.Message.getDefaultInstance()) return this;
        if (!other.getSender().isEmpty()) {
          Sender_ = other.Sender_;
          onChanged();
        }
        if (!other.getDate().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getHour().isEmpty()) {
          Hour_ = other.Hour_;
          onChanged();
        } 
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.MessageData.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.MessageData.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object Sender_ = "";
      /**
       * <pre>
       * Nome do Sender
       * </pre>
       *
       * <code>optional string Sender = 1;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = Sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          Sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Nome do Sender
       * </pre>
       *
       * <code>optional string Sender = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = Sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          Sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Nome do Sender
       * </pre>
       *
       * <code>optional string Sender = 1;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        Sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do Sender
       * </pre>
       *
       * <code>optional string Sender = 1;</code>
       */
      public Builder clearSender() {
        
        Sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do Sender
       * </pre>
       *
       * <code>optional string Sender = 1;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        Sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data de envio
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object Hour_ = "";
      /**
       * <pre>
       * Hour de envio
       * </pre>
       *
       * <code>optional string Hour = 3;</code>
       */
      public java.lang.String getHour() {
        java.lang.Object ref = Hour_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          Hour_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Hour de envio
       * </pre>
       *
       * <code>optional string Hour = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHourBytes() {
        java.lang.Object ref = Hour_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          Hour_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Hour de envio
       * </pre>
       *
       * <code>optional string Hour = 3;</code>
       */
      public Builder setHour(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        Hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hour de envio
       * </pre>
       *
       * <code>optional string Hour = 3;</code>
       */
      public Builder clearHour() {
        
        Hour_ = getDefaultInstance().getHour();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hour de envio
       * </pre>
       *
       * <code>optional string Hour = 3;</code>
       */
      public Builder setHourBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        Hour_ = value;
        onChanged();
        return this;
      }     

      public Builder setGroupBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
            
            group_ = value;
            onChanged();
            return this;
    }   

      private br.ufs.dcomp.ChatRabbitMQ.MessageData.Content Content_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.MessageData.Content, br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder, br.ufs.dcomp.ChatRabbitMQ.MessageData.ContentOrBuilder> ContentBuilder_;
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public boolean hasContent() {
        return ContentBuilder_ != null || Content_ != null;
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Content getContent() {
        if (ContentBuilder_ == null) {
          return Content_ == null ? br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.getDefaultInstance() : Content_;
        } else {
          return ContentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public Builder setContent(br.ufs.dcomp.ChatRabbitMQ.MessageData.Content value) {
        if (ContentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Content_ = value;
          onChanged();
        } else {
          ContentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public Builder setContent(
          br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder builderForValue) {
        if (ContentBuilder_ == null) {
          Content_ = builderForValue.build();
          onChanged();
        } else {
          ContentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public Builder mergeContent(br.ufs.dcomp.ChatRabbitMQ.MessageData.Content value) {
        if (ContentBuilder_ == null) {
          if (Content_ != null) {
            Content_ =
              br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.newBuilder(Content_).mergeFrom(value).buildPartial();
          } else {
            Content_ = value;
          }
          onChanged();
        } else {
          ContentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public Builder clearContent() {
        if (ContentBuilder_ == null) {
          Content_ = null;
          onChanged();
        } else {
          Content_ = null;
          ContentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.MessageData.ContentOrBuilder getContentOrBuilder() {
        if (ContentBuilder_ != null) {
          return ContentBuilder_.getMessageOrBuilder();
        } else {
          return Content_ == null ?
              br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.getDefaultInstance() : Content_;
        }
      }
      /**
       * <code>optional .ChatRabbitMQ.Content Content = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.MessageData.Content, br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder, br.ufs.dcomp.ChatRabbitMQ.MessageData.ContentOrBuilder> 
          getContentFieldBuilder() {
        if (ContentBuilder_ == null) {
          ContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              br.ufs.dcomp.ChatRabbitMQ.MessageData.Content, br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder, br.ufs.dcomp.ChatRabbitMQ.MessageData.ContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          Content_ = null;
        }
        return ContentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ChatRabbitMQ.Message)
    }

    // @@protoc_insertion_point(class_scope:ChatRabbitMQ.Message)
    private static final br.ufs.dcomp.ChatRabbitMQ.MessageData.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.MessageData.Message();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ChatRabbitMQ.MessageData.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatRabbitMQ.Content)
      com.google.protobuf.MessageOrBuilder { 

    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();    
    /**
     * <pre>
     * Sequência de bytes que compõe o Body da Message
     * </pre>
     *
     * <code>optional bytes Body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();

     /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();   
  }
  /**
   * Protobuf type {@code ChatRabbitMQ.Content}
   */
  public  static final class Content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatRabbitMQ.Content)
      ContentOrBuilder {
    // Use Content.newBuilder() to construct.
    private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Content() { 
      body_ = com.google.protobuf.ByteString.EMPTY; 
      type_ = ""; 
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            } 
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {

              body_ = input.readBytes();
              break;
            } 
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Content_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.class, br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder.class);
    } 
    
    public static final int body_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     * Sequência de bytes que compõe o Body da Message
     * </pre>
     *
     * <code>optional bytes Body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
     
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      } 
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.MessageData.Content)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.MessageData.Content other = (br.ufs.dcomp.ChatRabbitMQ.MessageData.Content) obj;

      boolean result = true; 
      result = result && getBody()
          .equals(other.getBody());
      result = result && getName()
      .equals(other.getName());
      result = result && getType()
      .equals(other.getType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode(); 
      hash = (37 * hash) + body_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();  
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.MessageData.Content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatRabbitMQ.Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatRabbitMQ.Content)
        br.ufs.dcomp.ChatRabbitMQ.MessageData.ContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Content_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.class, br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear(); 
        body_ = com.google.protobuf.ByteString.EMPTY; 
        type_ = "";  
        name_ = "";
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.internal_static_ChatRabbitMQ_Content_descriptor;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Content getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.getDefaultInstance();
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Content build() {
        br.ufs.dcomp.ChatRabbitMQ.MessageData.Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageData.Content buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.MessageData.Content result = new br.ufs.dcomp.ChatRabbitMQ.MessageData.Content(this); 
        result.body_ = body_; 
        result.type_ = type_; 
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.MessageData.Content) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.MessageData.Content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.MessageData.Content other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.MessageData.Content.getDefaultInstance()) return this;
       
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        } 
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.MessageData.Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.MessageData.Content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      } 
      
      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
     
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */ 

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Sequência de bytes que compõe o Body da Message
       * </pre>
       *
       * <code>optional bytes Body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o Body da Message
       * </pre>
       *
       * <code>optional bytes Body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o Body da Message
       * </pre>
       *
       * <code>optional bytes Body = 2;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }  
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ChatRabbitMQ.Content)
    }

    // @@protoc_insertion_point(class_scope:ChatRabbitMQ.Content)
    private static final br.ufs.dcomp.ChatRabbitMQ.MessageData.Content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.MessageData.Content();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageData.Content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Content>
        PARSER = new com.google.protobuf.AbstractParser<Content>() {
      public Content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Content> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Content> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ChatRabbitMQ.MessageData.Content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRabbitMQ_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRabbitMQ_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRabbitMQ_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRabbitMQ_Content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/Message.proto\022\014ChatRab" +
      "bitMQ\"p\n\010Message\022\017\n\007Sender\030\001 \001(\t\022\014\n\004da" +
      "ta\030\002 \001(\t\022\014\n\004Hour\030\003 \001(\t\022\r\n\005group\030\004 \001(\t\022(\n" +
      "\010Content\030\005 \001(\0132\026.ChatRabbitMQ.Content\"" +
      "5\n\010Content\022\014\n\004tipo\030\001 \001(\t\022\r\n\005Body\030\002 \001(\014" +
      "\022\014\n\004nome\030\003 \001(\tB)\n\031br.ufs.dcomp.ChatRabbi" +
      "tMQB\014MessageDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChatRabbitMQ_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatRabbitMQ_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRabbitMQ_Message_descriptor,
        new java.lang.String[] { "Sender", "Data", "Hour","Group", "Content", });
    internal_static_ChatRabbitMQ_Content_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChatRabbitMQ_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRabbitMQ_Content_descriptor,
        new java.lang.String[] { "Tipo", "Body", "Nome", });
  } 
}
